#!/bin/bash
# =================================================================
# deploy.sh — Executed directly by Jenkins on the same EC2 instance
# Requires these env vars to be pre-set by Jenkins:
#   MYSQL_ROOT_PASSWORD, MYSQL_PASSWORD, SPRING_MAIL_PASSWORD,
#   JAR_NAME, APP_PORT
# =================================================================

set -e

REMOTE_DIR="$(pwd)"
ENV_FILE="${REMOTE_DIR}/.env"

echo "🚀 Starting HRMS Backend Deployment..."
echo "   Directory : ${REMOTE_DIR}"
echo "   JAR       : ${JAR_NAME}"
echo "   Port      : ${APP_PORT}"

# Step 1: Write .env file (secrets injected by Jenkins)
echo "📝 Writing .env file..."
cat > "${ENV_FILE}" <<EOF
# Auto-generated by Jenkins deploy — DO NOT EDIT MANUALLY
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=workforce_db
MYSQL_USER=workforce_user
MYSQL_PASSWORD=${MYSQL_PASSWORD}
SPRING_PROFILES_ACTIVE=prod
APP_PORT=${APP_PORT:-8080}
SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-}
SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-}
JAR_NAME=${JAR_NAME}
EOF
chmod 600 "${ENV_FILE}"

# Step 2: Stop existing containers (graceful)
echo "🛑 Stopping existing containers..."
cd "${REMOTE_DIR}"
docker compose down --remove-orphans 2>/dev/null || true
sleep 3

# Step 3: Build & start containers
echo "🔨 Building Docker image and starting containers..."
docker compose --env-file "${ENV_FILE}" up -d --build

# Step 4: Wait for backend to be healthy
echo "⏳ Waiting for backend to become healthy (up to 90s)..."
ATTEMPTS=0
MAX_ATTEMPTS=18
until docker inspect --format='{{.State.Health.Status}}' workforce-backend 2>/dev/null | grep -q "healthy" || \
      curl -sf http://localhost:${APP_PORT:-8080}/api/auth/health > /dev/null 2>&1 || \
      [ $ATTEMPTS -ge $MAX_ATTEMPTS ]; do
    ATTEMPTS=$((ATTEMPTS + 1))
    echo "   Attempt ${ATTEMPTS}/${MAX_ATTEMPTS} — waiting 5s..."
    sleep 5
done

# Step 5: Show status
echo ""
echo "✅ Deployment complete! Container status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E "workforce|NAMES"

# Step 6: Tail last 20 lines of backend log
echo ""
echo "📋 Last 20 log lines from backend:"
docker logs workforce-backend --tail=20 || true
